from tkinter import *

window=Tk()
window.title("lable")
window.geometry("500x500+252+100")
lab1=Label(window,bitmap="error",bg="#ffffff")
lab2=Label(window,bitmap="hourglass",bg="#ffffff")
lab3=Label(window,bitmap="info",bg="#ffffff")
lab4=Label(window,bitmap="questhead",bg="#ffffff")
lab5=Label(window,bitmap="question",bg="#ffffff")
lab6=Label(window,bitmap="warning",bg="#ffffff")
lab7=Label(window,bitmap="gray12",bg="#ffffff")
lab8=Label(window,bitmap="gray25",bg="#ffffff")
lab9=Label(window,bitmap="gray50",bg="#ffffff")
lab10=Label(window,bitmap="gray75",bg="#ffffff")
lab1.pack()
lab2.pack()
lab3.pack()
lab4.pack()
lab5.pack()
lab6.pack()
lab7.pack()
lab8.pack()
lab9.pack()
lab10.pack()
window.mainloop()